name: Virtual test (macos)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
jobs:
  virtual-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: macos
    steps:
      - uses: actions/checkout@v4
      - name: Run virtual test
        run: bash tests/virtual-test.sh
